### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by 0522ash** [0522ash/protospace-34453#1]
#URL
https://protospace-34453.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **プロトタイプ編集ページにて、空の入力欄がある場合は、編集できずにそのページに留まるようにしましょう**
現状ではエラー画面に遷移してしまいます

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
ご提出ありがとうございます！
前回依頼箇所の修正確認ができました🎉

恐れ入りますがもう一点、修正をお願いしたい箇所がございました。

[修正依頼箇所]
- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移するようにしましょう**
プロトタイプ名をクリックしたときは遷移しないため、修正をお願いします！

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう！
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
